CREATE TABLE ONAP_DATA (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	CELL_NAME VARCHAR(100) NOT NULL,
	MEASUREMENT_TYPE VARCHAR(100) NOT NULL,
	MEASUREMENT_VALUE INT NOT NULL,
	BEGIN_DATE DATETIMEOFFSET NOT NULL,
	END_DATE DATETIMEOFFSET NOT NULL,
	GRANULARITY INT NOT NULL
)

CREATE TABLE FOLLOWED_METRICS (
	MEASUREMENT_TYPE VARCHAR(100) PRIMARY KEY,
	MEASUREMENT_UNITS VARCHAR(10)
)