CREATE TABLE ONAP_DATA (
	ID BIGINT IDENTITY(1, 1) PRIMARY KEY,
	NODE_NAME VARCHAR(255) NOT NULL
	OBJECT_TYPE VARCHAR(20) NOT NULL,
	OBJECT_ID VARCHAR(255) NOT NULL,
	MEASUREMENT_TYPE VARCHAR(100) NOT NULL,
	MEASUREMENT_VALUE BIGINT NOT NULL,
	BEGIN_DATE DATETIMEOFFSET NOT NULL,
	GRANULARITY INT NOT NULL
);

CREATE TABLE Development.dbo.METRICS (
	ID int IDENTITY(1,1) PRIMARY KEY,
	NAME varchar(100) NOT NULL,
	TYPE varchar(20) NOT NULL,
	COMPONENTS varchar(500) NOT NULL,
	FORMULA varchar(700) NOT NULL,
	AGGREGATION varchar(5) NOT NULL,
	UNITS varchar(10) NOT NULL
);

CREATE TABLE FOLLOWED_INDICATORS (
	MEASUREMENT_TYPE VARCHAR(100) PRIMARY KEY,
	MEASUREMENT_UNITS VARCHAR(10)
);