CREATE TABLE ONAP_DATA (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NODE_NAME VARCHAR(255) NOT NULL
	OBJECT_TYPE VARCHAR(20) NOT NULL,
	OBJECT_ID VARCHAR(255) NOT NULL,
	MEASUREMENT_TYPE VARCHAR(100) NOT NULL,
	MEASUREMENT_VALUE INT NOT NULL,
	BEGIN_DATE DATETIMEOFFSET NOT NULL,
	GRANULARITY INT NOT NULL
)

CREATE TABLE FOLLOWED_METRICS (
	MEASUREMENT_TYPE VARCHAR(100) PRIMARY KEY,
	MEASUREMENT_UNITS VARCHAR(10)
)