INSERT INTO dbo.FOLLOWED_INDICATORS (MEASUREMENT_TYPE) VALUES
	 ('VS.NCAV.DENOM_CELL_AVAIL'),
	 ('VS.NCAV.NR_CELL_PLAN_UNAVAIL_SAMPLES'),
	 ('VS.NCAV.SAMPLES_CELL_AVAIL'),
	 ('VS.NCUPNRG.DL_PRB_USED_DATA_NRG'),
	 ('VS.NCUPNRG.DL_PRB_UTIL_RATIO_DNOM'),
	 ('VS.NCUPNRG.DL_PRB_UTIL_SLOT_MAX_NRG'),
	 ('VS.NCUPNRG.UL_PRB_USED_DATA_NRG'),
	 ('VS.NCUPNRG.UL_PRB_UTIL_RATIO_DNOM'),
	 ('VS.NRASU.PDCP_SDU_USDAT_VOL_DL_SA_PLMN'),
	 ('VS.NRASU.PDCP_SDU_USDAT_VOL_UL_SA_PLMN'),
	 ('VS.SBTS_RFM_Energy_Monitoring.MAX_INPUT_VOLTAGE_IN_RF'),
	 ('VS.SBTS_RFM_Energy_Monitoring.MIN_INPUT_VOLTAGE_IN_RF'),
	 ('VS.SBTS_RFM_Energy_Monitoring.RU_AVG_PWR_USAGE');


INSERT INTO dbo.METRICS (NAME,TYPE,COMPONENTS,FORMULA,AGGREGATION,UNITS) VALUES
	 ('DL_Traffic_Volume','RAW','VS.NRASU.PDCP_SDU_USDAT_VOL_DL_SA_PLMN','VS_NRASU_PDCP_SDU_USDAT_VOL_DL_SA_PLMN','SUM','Kb'),
	 ('UL_Traffic_Volume','RAW','VS.NRASU.PDCP_SDU_USDAT_VOL_UL_SA_PLMN','VS_NRASU_PDCP_SDU_USDAT_VOL_UL_SA_PLMN','SUM','Kb'),
	 ('DL_Throughput','COMPOSITE','VS.NRASU.PDCP_SDU_USDAT_VOL_DL_SA_PLMN','VS_NRASU_PDCP_SDU_USDAT_VOL_DL_SA_PLMN * 8 / GRANULARITY','SUM','KB/s'),
	 ('UL_Throughput','COMPOSITE','VS.NRASU.PDCP_SDU_USDAT_VOL_UL_SA_PLMN','VS_NRASU_PDCP_SDU_USDAT_VOL_UL_SA_PLMN * 8 / GRANULARITY','SUM','KB/s'),
	 ('PRB_DL','COMPOSITE','VS.NCUPNRG.DL_PRB_USED_DATA_NRG,VS.NCUPNRG.DL_PRB_UTIL_RATIO_DNOM','VS_NCUPNRG_DL_PRB_USED_DATA_NRG / VS_NCUPNRG_DL_PRB_UTIL_RATIO_DNOM * 100','AVG','%'),
	 ('PRB_UL','COMPOSITE','VS.NCUPNRG.UL_PRB_USED_DATA_NRG,VS.NCUPNRG.UL_PRB_UTIL_RATIO_DNOM','VS_NCUPNRG_UL_PRB_USED_DATA_NRG / VS_NCUPNRG_UL_PRB_UTIL_RATIO_DNOM * 100','AVG','%'),
	 ('Peak_PRB','RAW','VS.NCUPNRG.DL_PRB_UTIL_SLOT_MAX_NRG','VS_NCUPNRG_DL_PRB_UTIL_SLOT_MAX_NRG','MAX','%'),
	 ('Cell_Availability','COMPOSITE','VS.NCAV.SAMPLES_CELL_AVAIL,VS.NCAV.DENOM_CELL_AVAIL,VS.NCAV.NR_CELL_PLAN_UNAVAIL_SAMPLES','VS_NCAV_SAMPLES_CELL_AVAIL / (VS_NCAV_DENOM_CELL_AVAIL - VS_NCAV_NR_CELL_PLAN_UNAVAIL_SAMPLES) * 100','SUM','%'),
	 ('RFM_Energy_Monitoring','COMPOSITE','VS.SBTS_RFM_Energy_Monitoring.MIN_INPUT_VOLTAGE_IN_RF,VS.SBTS_RFM_Energy_Monitoring.MAX_INPUT_VOLTAGE_IN_RF','(VS_SBTS_RFM_Energy_Monitoring_MIN_INPUT_VOLTAGE_IN_RF + VS_SBTS_RFM_Energy_Monitoring_MAX_INPUT_VOLTAGE_IN_RF) / 2000','AVG','V'),
	 ('RFM_Energy_Consumption','RAW','VS.SBTS_RFM_Energy_Monitoring.RU_AVG_PWR_USAGE','VS_SBTS_RFM_Energy_Monitoring_RU_AVG_PWR_USAGE / 1000','SUM','W');
