INSERT INTO Development.dbo.FOLLOWED_METRICS (MEASUREMENT_TYPE,MEASUREMENT_UNITS) VALUES
	 ('VS.NCAV.DENOM_CELL_AVAIL','%'),
	 ('VS.NCAV.SAMPLES_CELL_AVAIL','%'),
	 ('VS.NCUPNRG.DL_PRB_USED_DATA_NRG','N/A'),
	 ('VS.NCUPNRG.DL_PRB_UTIL_RATIO_DNOM','N/A'),
	 ('VS.NCUPNRG.DL_PRB_UTIL_SLOT_MAX_NRG','%'),
	 ('VS.NCUPNRG.UL_PRB_UTIL_RATIO_DNOM','N/A'),
	 ('VS.NRASU.PDCP_SDU_USDAT_VOL_DL_SA_PLMN','Kb/s'),
	 ('VS.NRASU.PDCP_SDU_USDAT_VOL_UL_SA_PLMN','Kb/s'),
	 ('VS.SBTS_RFM_Energy_Monitoring.MAX_INPUT_VOLTAGE_IN_RF','0.5mV'),
	 ('VS.SBTS_RFM_Energy_Monitoring.MIN_INPUT_VOLTAGE_IN_RF','0.5mV');
INSERT INTO Development.dbo.FOLLOWED_METRICS (MEASUREMENT_TYPE,MEASUREMENT_UNITS) VALUES
	 ('VS.SBTS_RFM_Energy_Monitoring.RU_AVG_PWR_USAGE','mW');
