INSERT INTO Development.dbo.FOLLOWED_METRICS (MEASUREMENT_TYPE,MEASUREMENT_UNITS) VALUES
     (N'VS.NCAV.DENOM_CELL_AVAIL',N'%'),
     (N'VS.NCAV.NR_CELL_PLAN_UNAVAIL_SAMPLES',N'N/A'),
     (N'VS.NCAV.SAMPLES_CELL_AVAIL',N'%'),
     (N'VS.NCUPNRG.DL_PRB_USED_DATA_NRG',N'N/A'),
     (N'VS.NCUPNRG.DL_PRB_UTIL_RATIO_DNOM',N'N/A'),
     (N'VS.NCUPNRG.DL_PRB_UTIL_SLOT_MAX_NRG',N'%'),
     (N'VS.NCUPNRG.UL_PRB_USED_DATA_NRG',N'N/A'),
     (N'VS.NCUPNRG.UL_PRB_UTIL_RATIO_DNOM',N'N/A'),
     (N'VS.NRASU.PDCP_SDU_USDAT_VOL_DL_SA_PLMN',N'Kb/s'),
     (N'VS.NRASU.PDCP_SDU_USDAT_VOL_UL_SA_PLMN',N'Kb/s');
INSERT INTO Development.dbo.FOLLOWED_METRICS (MEASUREMENT_TYPE,MEASUREMENT_UNITS) VALUES
     (N'VS.SBTS_RFM_Energy_Monitoring.MAX_INPUT_VOLTAGE_IN_RF',N'0.5mV'),
     (N'VS.SBTS_RFM_Energy_Monitoring.MIN_INPUT_VOLTAGE_IN_RF',N'0.5mV'),
     (N'VS.SBTS_RFM_Energy_Monitoring.RU_AVG_PWR_USAGE',N'mW');
